# numpy operations 

## array operations

In [1]:
import numpy as np

In [5]:
# genrating a numpy array
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [14]:
#  adding a integer to each item of array 

print(arr + 1)
print(arr - 1)
print(arr * 2)
#print(arr / 0) # Error triggred 
print(arr / 1) # Error triggred 



[ 1  2  3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7  8  9]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
