# numpy operations 

## array operations

In [1]:
import numpy as np

In [5]:
# genrating a numpy array
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [20]:
#  adding a integer to each item of array 

print(arr + 1)
print(arr - 1)
print(arr * 2)
#print(arr / 0) # Error triggred 
print(arr / 1) # Error triggred 
print(1/arr) # Error triggred
print(arr ** 2) # squaring 


[ 1  2  3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7  8  9]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]
[  0   1   4   9  16  25  36  49  64  81 100]


D:\programs\conda\envs\ml\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide
  


In [18]:
# adding a array to itself or to other array

print(arr+arr)
print(arr-arr)
print(arr*arr)
print(arr/arr) 



[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


D:\programs\conda\envs\ml\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


In [33]:
# numpy funtions

print(np.sqrt(arr))
print(np.max(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
10
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]


D:\programs\conda\envs\ml\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys
